### ISSUE TITLE
Persitency for live iso image how-to ?

### ISSUE THREAD

**Issue by j-landru** [rancher/elemental-toolkit#1271]
**Is your feature request related to a problem? Please describe.**

"C.I.R.R.U.S. : Cloud Iac Reservoir de Ressources Unifiées pour Salles de tp"

CIRRUS will be a k3s IPv6 only cluster dedicated to computer science and network educational labs.

On cirrus all cluster nodes, (bare metal or cloned VM) k3s server as well as agent, will  share the same immutable unique live iso image. 
* cirrus-os is a c0S-toolkit derivative called abcd4cirrus-os : ***a***lpine ***b***based ***c***OS ***d***erivative for cirrus-os
* cirrus node unique image is an immutable live iso file built with cOS-toolkit

All tools and services like k3s will be embedded on that unique shared live iso image. No service install nor OS updates or upgrades need to be done, even using that neat air-gap update cOS mode based on  ```elemental```, on each node when 1st booting. 
Node updates will be done by simply restarting node on a new iso image, eventual rollback only need to point to the previous iso image.  On a cluster with N nodes, I don't want to install nor upgrade N times, even with an automated airgap mode facility, when N will scale up.
So node customization and persistent data (config files, network interfaces conf, k3s state or log files)  need to be overlayed on COS_PERSISTENT labeled block device of cos-toolkit facility on a auxiliary block device (usb stick or other), host SSD and disks will be fully dedicated to  a distributed storage backend (probably Rook/ceph or Longhorn based). I don't want to use node disk or partition to locally install cos-derivative.

**Describe the solution you'd like**

A simple way to activate cOS persistence on an auxiliary labeled COS_PERSISTENT block device when live iso booting like some common live demo distrib 

(similar to what I tried to to do with auxiliary DELTA disk on k3os, see https://github.com/rancher/k3os/discussions/832 for a similar feature request)

**Describe alternatives you've considered**

Trying to activate persitency with cOS cloud-init facility with no success. What do I miss in the doc ? I must say I'm a newby about ```cloud-init```.
 - adding persistency in my image following [system/immutable-rootfs](https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/packages/system-immutable-rootfs/) and [build ISO](https://rancher-sandbox.github.io/cos-toolkit-docs/docs/creating-derivatives/build_iso/) 
 - customize grub-cfg or syslinux.cfg to remove ```rd.cos.disable```` kernel parm
But it doesn't work, live boot initamfs step timeout entering in "```emergency mode```"..."```Press Enter for maintenance``` which is a symptom of dracut failed to determinate rootfs

Probably not the good way...
What I understand, nested alpine squashfs image has probably cOS presistency through ```/system/oem``` or  ```/run/cos/cos-layout.env``` files from the build but iso primary image and its initramfs has no support for cloud-init persistency directive.

**Additional context**

Managing  ```toram``` boot parameter would be a plus.

**Comment by mudler** [comment]
Hi @j-landru the project looks really great, and thanks for the feedback!

This should be already possible, and it is documented here: https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/packages/system-immutable-rootfs/#configuration-with-an-environment-file

To configure the booting layout add a cloud config file in `/system/oem`, for example `/system/oem/99-persistency.yaml` (not tested) in the image:

```yaml
name: "Configure persistent dirs bind-mounts"
stages:
  rootfs.after:
    - if: '[ -f "/run/cos/live_mode" ]'
      name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local"
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
           ....
        PERSISTENT_STATE_BIND: "true"
```
