### ISSUE TITLE
Use a single repositories list in manifest.yaml

### ISSUE THREAD

**Issue by davidcassany** [rancher/elemental-toolkit#1346]
Currently for `build-disk` command the repositories can be set in two different places under each arch specific stanza and globally.
I think this is error prone, confusing and adds some extra logic in elemental. I believe we should have only a single repositories list and eventually filter them by arch, so each architecture sees only the matching repositories at build time.

This is a currently valid

```yaml
raw_disk:
  x86_64:
    # which packages to install and the target to install them at
    packages:
      - name: system/myos
        target: efi
  aarch64:
    repositories:
     - uri: quay.io/costoolkit/releases-green-arm64
    packages:
      - name: system/grub2-efi-image
        target: efi

repositories:
- uri: registry.org/my/repo
```

I suggest to change it to:

```yaml
raw_disk:
  x86_64:
    # which packages to install and the target to install them at
    packages:
      - name: system/myos
        target: efi
  aarch64:
    packages:
      - name: system/grub2-efi-image
        target: efi

repositories:
- uri: registry.org/my/repo
  arch: "x86_84"
- uri: "quay.io/costoolkit/releases-green-arm64"
  arch: "aarch64"
```
