### ISSUE TITLE
Improve sizes in config

### ISSUE THREAD

**Issue by frelon** [rancher/elemental-toolkit#1769]
In the following config it's hard to know what "size" represents without the comment.

```yaml
install:
  # size in MiB
  partitions:
    oem:
      label: COS_OEM
      size: 60
      fs: ext4
```

I think we should use something like https://github.com/docker/go-units to parse sizes instead, making the config look like this:

```yaml
install:
  partitions:
    oem:
      label: COS_OEM
      size: 60MiB
      fs: ext4
```

Also this must be backwards-compatible and parse in MiB if no unit is specified.
