### ISSUE TITLE
A potential bug in `NewElementalPartitionsFromList` which caused upgrade error code 33

### ISSUE THREAD

**Issue by w13915984028** [rancher/elemental-toolkit#1827]
**elemental-toolkit version:**

Latest

**CPU architecture, OS, and Version:**

**Describe the bug**

Error code 33 was encountered in Harvester upgrade.

```
ERRO[2023-09-13T12:02:42Z] Invalid upgrade command setup undefined state partition 
elemental upgrade failed with return code: 33
+ ret=33


cdo path:
			spec, err := config.ReadUpgradeSpec(cfg, cmd.Flags()) //========================
			if err != nil {
				cfg.Logger.Errorf("Invalid upgrade command setup %v", err) //========================
				return elementalError.NewFromError(err, elementalError.ReadingSpecConfig) //========================
			}
```

Please refer https://github.com/harvester/harvester/issues/4526#issuecomment-1721152697

```
// NewElementalPartitionsFromList fills an ElementalPartitions instance from given
// partitions list. First tries to match partitions by partition label, if not,
// it tries to match partitions by filesystem label
func NewElementalPartitionsFromList(pl PartitionList, state *InstallState) ElementalPartitions {
	ep := ElementalPartitions{}

	lm := map[string]string{
		constants.EfiPartName:        constants.EfiLabel,
		constants.OEMPartName:        constants.OEMLabel,
		constants.RecoveryPartName:   constants.RecoveryLabel,
		constants.StatePartName:      constants.StateLabel,
		constants.PersistentPartName: constants.PersistentLabel,
	}
	if state != nil {
		for k := range lm {
			if state.Partitions[k] != nil {
				lm[k] = state.Partitions[k].FSLabel  /// the state.Partitions[k].FSLabel may be nil
			}
		}
	}
```	

**To Reproduce**

Harvesrter Upgrade.

Not sure why, the `/host/run/initramfs/cos-state/state.yaml ` is missing the `FSLabel`, and it further caused error code 33
```
pre-harvester01-01:/ # cat /host/run/initramfs/cos-state/state.yaml 
# Autogenerated file by elemental client, do not edit

date: "2023-09-13T08:31:42Z"
state:
    active:
        source: dir:///tmp/tmp.01deNrXNEC
        label: COS_ACTIVE
        fs: ext2
    passive: null
```
**Expected behavior**

**Logs**

**Additional context**
