### ISSUE TITLE
Root password lost after an OS upgrade

### ISSUE THREAD

**Issue by ldevulder** [rancher/elemental-toolkit#1982]
**elemental-toolkit version:** 1.1.1

**elemental-operator version:** 1.5.0 (Dev)

**CPU architecture, OS, and Version:** x86, Elemental OS v2.0.2 (based on SLE Micro 5.5)

**Describe the bug**

After an upgrade from Elemental OS v2.0.2 (Stable) to v2.1.0 (Dev) with `managedOSVersionName` method the root password previously configured during deployment is not working anymore. Erased?

**To Reproduce**

Install Rancher Manager v2.8.2, `elemental-operator` Dev (1.5.0), deploy a simple one node cluster with Elemental OS Stable (2.0.2) and update it to Dev (2.1.0) with `ManagedOSVersionName`. Wait for the node to reboot and try to connect with either ssh on directly on the console (for baremetal of VM).

`ManagedOSImage` used:
```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSImage
metadata:
  name: with-os-version-name
  namespace: fleet-default
spec:
  clusterTargets:
    - clusterName: cluster-k3s
  managedOSVersionName: v2.1.0-unstable
```

**Expected behavior**

OS upgrade done and root connection still working.

**Logs**

[elemental-operator.log](https://github.com/rancher/elemental-toolkit/files/14434018/elemental-operator.log)

**Additional context**

N/A
