### ISSUE TITLE
systemd-sysctl stopped working at boot 

### ISSUE THREAD

**Issue by anmazzotti** [rancher/elemental-toolkit#2167]
**elemental-toolkit version:** `nightly`

**Describe the bug**

I did setup `/etc/sysctl.d/99-k8s.conf` as follows:
```
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_forward = 1
net.ipv4.conf.all.forwarding = 1
```
This used to work fine and I think it broke somewhere in July 2024.
Can only be reproduced on `nightly`, not on `2.1.0` for example.

`systemd-sysctl` doesn't seem to work anymore at boot.
Config is not applied.
This only happens on the installed/active system, it works as expected from the live media.

**Logs**
[live-logs.txt](https://github.com/user-attachments/files/16759875/live-logs.txt)
[active-logs.txt](https://github.com/user-attachments/files/16759876/active-logs.txt)

**Additional context**
As a workaround, restarting `systemd-sysctl` at boot seems to work fine
```yaml
name: "Workaround for systemd-sysctl missing boot"
stages:
  boot:
  - commands:
    - systemctl restart systemd-sysctl
```
