### ISSUE TITLE
Custom Image doesn't boot after install

### ISSUE THREAD

**Issue by max06** [rancher/elemental-toolkit#2249]
Good morning... again 😅 

I'm currently building an elemental distribution based on ubuntu 24.04 - on your orange flavor. It took some time to get used to this toolkit, as well as some fixes in the orange dockerfile to make things work.

So far I have a working build pipeline throwing out container and iso oci images, and an accompanying channel image. 
Said images, prepared by rancher, boot perfectly fine in my virtual machines. 
Installation works and finishes without errors. 

After reboot I get greeted by grub containing 2 items in its menu. And then it falls apart: 
![image](https://github.com/user-attachments/assets/1d4d456a-9d16-4e36-bea5-df8c4d894a77)
Booting the recovery works though.

I know you're not supporting foreign distributions, and I wouldn't even be (seriously) mad if you close this issue. Maybe just a little bit... for a while... 😄  

If you are interested: Awesome!

Here's the channel manifest: 

```yaml
apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-ubuntu-bare-metal
  namespace: fleet-default
spec:
  deleteNoLongerInSyncVersions: false
  options:
    image: ghcr.io/max06/elemental-ubuntu-channel:bare-metal
  syncInterval: 10m
  type: custom
``` 

The repo can be found [here](https://github.com/max06/elemental-ubuntu). It's mostly a mix of the orange Dockerfile and your elemental-repository for the config files. The pipeline uses the Makefile.

The whole thing is work in progress, some parts are missing. I just wanted to solve this issue before moving on. I just don't really have a clue at this moment. 

Thank you very much!
